[package]
authors = { workspace = true }
edition = { workspace = true }
name = "spk-cmd-debug"
version = { workspace = true }

[dependencies]
anyhow = "1.0"
async-trait = "0.1"
clap = { workspace = true, features = ["derive", "env"] }
futures = { workspace = true }
spfs = { version = '0.34.6', path = "../../spfs" }
spk-cli-common = { path = '../common' }
spk-exec = { path = '../../spk-exec' }
spk-schema = { path = '../../spk-schema' }
spk-storage = { path = '../../spk-storage' }
tokio = { version = "1.20", features = ["rt"] }
tracing = "0.1.35"
