[package]
authors = { workspace = true }
edition = { workspace = true }
name = "spk-cmd-debug"
version = { workspace = true }
license-file = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }
readme = { workspace = true }
description = { workspace = true }

[lints]
workspace = true

[dependencies]
anyhow = "1.0"
async-trait = "0.1"
clap = { workspace = true, features = ["derive", "env"] }
futures = { workspace = true }
miette = { workspace = true, features = ["fancy"] }
spfs = { workspace = true }
spk-cli-common = { workspace = true }
spk-exec = { workspace = true }
spk-schema = { workspace = true }
spk-storage = { workspace = true }
tokio = { version = "1.43", features = ["rt"] }
tracing = "0.1.35"
