[package]
authors = ["Ryan Bottriell <rbottriell@imageworks.com>"]
edition = { workspace = true }
name = "spk-solve-package-iterator"
version = { workspace = true }

[dependencies]
async-trait = { workspace = true }
dyn-clone = { workspace = true }
futures = { workspace = true }
once_cell = { workspace = true }
spk-solve-solution = { path = "../solution" }
spk-schema = { path = "../../../spk-schema" }
spk-storage = { path = "../../../spk-storage" }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["rt"] }
tracing = { workspace = true }

[dev-dependencies]
itertools = "0.10"
rstest = { workspace = true }
spk-solve = { path = "../.." }
