[package]
authors = { workspace = true }
edition = { workspace = true }
name = "spk-solve-package-iterator"
version = { workspace = true }

[features]
migration-to-components = [
	"spk-config/migration-to-components",
	"spk-solve-solution/migration-to-components",
	"spk-schema/migration-to-components",
	"spk-storage/migration-to-components",
]

[dependencies]
async-trait = { workspace = true }
dyn-clone = { workspace = true }
futures = { workspace = true }
glob = { workspace = true }
once_cell = { workspace = true }
spk-config = { path = "../../../spk-config" }
spk-solve-solution = { path = "../solution" }
spk-schema = { path = "../../../spk-schema" }
spk-storage = { path = "../../../spk-storage" }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["rt"] }
tracing = { workspace = true }

[dev-dependencies]
itertools = "0.10"
rstest = { workspace = true }
spk-solve-macros = { path = "../macros" }
