[package]
authors = { workspace = true }
edition = { workspace = true }
name = "spk-solve-package-iterator"
version = { workspace = true }

[lints]
workspace = true

[features]
migration-to-components = [
    "spk-config/migration-to-components",
    "spk-solve-solution/migration-to-components",
    "spk-schema/migration-to-components",
    "spk-storage/migration-to-components",
]

[dependencies]
async-trait = { workspace = true }
dyn-clone = { workspace = true }
futures = { workspace = true }
glob = { workspace = true }
once_cell = { workspace = true }
spk-config = { workspace = true }
spk-solve-solution = { workspace = true }
spk-schema = { workspace = true }
spk-storage = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["rt"] }
tracing = { workspace = true }
miette = { workspace = true }

[dev-dependencies]
itertools = { workspace = true }
rstest = { workspace = true }
spk-solve-macros = { workspace = true }
