[package]
authors = { workspace = true }
edition = { workspace = true }
name = "spk-cmd-make-recipe"
version = { workspace = true }

[dependencies]
anyhow = "1.0"
async-trait = "0.1"
clap = { workspace = true, features = ["derive", "env"] }
spk-cli-common = { path = '../common' }
spk-schema = { path = '../../spk-schema' }
spk-schema-liquid = { path = '../../spk-schema/crates/liquid' }
tracing = "0.1.35"
