[package]
authors = { workspace = true }
edition = { workspace = true }
name = "spfs-cli-render"
version = "0.34.6"

[[bin]]
name = "spfs-render"
path = "src/cmd_render.rs"

[features]
sentry = ["spfs-cli-common/sentry"]

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true }
dunce = { workspace = true }
futures = { workspace = true }
serde_json = { workspace = true }
spfs = { path = "../../spfs" }
spfs-cli-common = { path = "../common" }
strum = { workspace = true, features = ["derive"] }
tokio = { version = "1.20", features = ["rt", "rt-multi-thread"] }
tracing = { workspace = true }
