[package]
authors = { workspace = true }
edition = { workspace = true }
name = "spfs-encoding"
version = "0.34.6"

[dependencies]
data-encoding = "2.3"
ring = "0.16.15"
serde = { workspace = true, features = ["derive"] }
tokio = { version = "1.20", features = [
    "io-util",
    "io-std",
] }
thiserror = { workspace = true }

[dev-dependencies]
rstest = { version = "0.15.0", default_features = false }
rand = "0.8.5"
