[package]
authors = { workspace = true }
edition = { workspace = true }
name = "spk-cmd-render"
version = { workspace = true }

[lints]
workspace = true

[dependencies]
miette = { workspace = true, features = ["fancy"] }
async-trait = { workspace = true }
clap = { workspace = true }
dunce = { workspace = true }
spfs = { path = "../../spfs" }
spk-cli-common = { path = '../common' }
spk-exec = { path = '../../spk-exec' }
spk-storage = { path = '../../spk-storage' }
tokio = { workspace = true, features = ["rt"] }
tracing = { workspace = true }
