[package]
authors = { workspace = true }
edition = { workspace = true }
name = "spk-cmd-render"
version = { workspace = true }

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
clap = { workspace = true }
spfs = { version = '0.34.6', path = "../../spfs" }
spk-cli-common = { path = '../common' }
spk-exec = { path = '../../spk-exec' }
spk-storage = { path = '../../spk-storage' }
tokio = { workspace = true, features = ["rt"] }
tracing = { workspace = true }
