[package]
authors = { workspace = true }
name = "spk-config"
edition = { workspace = true }
version = { workspace = true }

[features]
migration-to-components = []

[dependencies]
config = { workspace = true }
dirs = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
once_cell = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
whoami = { workspace = true }

[dev-dependencies]
rstest = "0.15.0"
