[package]
authors = { workspace = true }
edition = { workspace = true }
name = "spk-cli-group3"
version = { workspace = true }

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
clap = { workspace = true }
colored = { workspace = true }
futures = { workspace = true }
spfs = { path = "../../spfs" }
spk-cli-common = { path = '../common' }
spk-storage = { path = '../../spk-storage' }
spk-schema = { path = '../../spk-schema' }
spfs-cli-common = { path = '../../spfs-cli/common' }
tracing = { workspace = true }
tokio = "1.20"

[dev-dependencies]
tar = "0.4.3"
spk-build = { path = '../../spk-build' }
rstest = { workspace = true }
