[package]
authors = ["Ryan Bottriell <rbottriell@imageworks.com>"]
edition = "2021"
name = "spk-cmd-env"
version = "0.36.0"

[lib]
name = "spk_cmd_env"
path = "src/lib.rs"

[dependencies]
anyhow = "1.0"
async-trait = "0.1"
clap = { version = "3.2", features = ["derive", "env"] }
spfs = { version = '0.34.6', path = "../../spfs" }
spk-cli-common = { path = '../common' }
spk-exec = { path = '../../spk-exec' }
tokio = { version = "1.20", features = ["rt"] }
tracing = "0.1.35"

[target.'cfg(target_os = "linux")'.dependencies]
nix = "0.24.1"
