[package]
authors = { workspace = true }
edition = { workspace = true }
name = "spk-schema-tera"
version = { workspace = true }
license-file = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }
readme = { workspace = true }
description = { workspace = true }

[lints]
workspace = true

[features]
migration-to-components = ["spk-schema-foundation/migration-to-components"]

[dependencies]
miette = { workspace = true }
once_cell = { workspace = true }
regex = "1.6.0"
serde = "1.0"
serde_json = "1.0"
spk-schema-foundation = { workspace = true }
tera = "1.19.1"
thiserror = { workspace = true }
tracing = "0.1.35"

[dev-dependencies]
rstest = "0.15.0"
miette = { workspace = true, features = ["fancy"] }
