[package]
authors = ["Ryan Bottriell <rbottriell@imageworks.com>"]
edition = { workspace = true }
name = "spk-schema-ident"
version = { workspace = true }

[dependencies]
colored = { workspace = true }
format_serde_error = { version = "0.3", default_features = false, features = [
    "serde_yaml",
    "colored",
] }
itertools = "0.10"
nom = { workspace = true }
nom-supreme = { workspace = true }
relative-path = "1.3"
serde = { workspace = true, features = ["derive"] }
serde_yaml = "0.8.17"
spk-schema-foundation = { path = "../foundation" }
thiserror = { workspace = true }

[dev-dependencies]
data-encoding = "2.3"
proptest = "1.0.0"
rstest = { workspace = true }
