[package]
authors = ["Ryan Bottriell <rbottriell@imageworks.com>"]
edition = "2021"
name = "spk-cmd-install"
version = "0.36.0"

[lib]
name = "spk_cmd_install"
path = "src/lib.rs"

[dependencies]
anyhow = "1.0"
async-trait = "0.1"
clap = { version = "3.2", features = ["derive", "env"] }
colored = "2.0.0"
futures = "0.3.9"
spk-cli-common = { path = '../common' }
spk-exec = { path = '../../spk-exec' }
spk-foundation = { path = '../../spk-foundation' }
tokio = { version = "1.20", features = ["rt"] }
