[package]
authors = { workspace = true }
edition = { workspace = true }
name = "spk-cmd-install"
version = { workspace = true }

[lints]
workspace = true

[dependencies]
miette = { workspace = true, features = ["fancy"] }
async-trait = { workspace = true }
clap = { workspace = true }
colored = { workspace = true }
futures = { workspace = true }
spk-cli-common = { path = '../common' }
spk-exec = { path = '../../spk-exec' }
spk-schema = { path = '../../spk-schema' }
tokio = { workspace = true, features = ["rt"] }
