[package]
authors = ["Ryan Bottriell <rbottriell@imageworks.com>"]
edition = { workspace = true }
name = "spk-build"
version = { workspace = true }

[features]
sentry = ["spk-solve/sentry"]

[dependencies]
futures = "0.3.9"
relative-path = "1.3"
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
serde_yaml = "0.8.17"
spfs = { version = '0.34.6', path = "../spfs" }
spk-exec = { path = "../spk-exec" }
spk-solve = { path = "../spk-solve" }
spk-schema = { path = "../spk-schema" }
spk-schema-validators = { path = "../spk-schema/crates/validators" }
spk-storage = { path = "../spk-storage" }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["rt"] }
tracing = { workspace = true }

[dev-dependencies]
rstest = { workspace = true }
serde_yaml = "0.8.17"
tar = "0.4.30"
tempfile = { workspace = true }
