[package]
authors = ["Ryan Bottriell <rbottriell@imageworks.com>"]
edition = "2021"
name = "spk-build"
version = "0.36.0"

[features]
sentry = ["spk-solve/sentry"]

[dependencies]
itertools = "0.10.3"
relative-path = "1.3"
serde = { version = "1.0.117", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.8.17"
spfs = { version = '0.34.6', path = "../spfs" }
spk-exec = { path = "../spk-exec" }
spk-solve = { path = "../spk-solve" }
spk-schema = { path = "../spk-schema" }
spk-storage = { path = "../spk-storage" }
thiserror = "1.0"
tokio = { version = "1.20", features = ["rt"] }
tracing = "0.1.35"

[dev-dependencies]
rstest = "0.15.0"
serde_yaml = "0.8.17"
tar = "0.4.30"
tempfile = "3.3"
