[package]
authors = ["Ryan Bottriell <rbottriell@imageworks.com>"]
edition = { workspace = true }
name = "spk-cli-group1"
version = { workspace = true }

[features]
sentry = ["spk-solve/sentry"]

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
clap = { workspace = true }
colored = { workspace = true }
futures = "0.3.9"
itertools = "0.10"
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
serde_yaml = "0.8.17"
spfs = { version = '0.34.6', path = "../../spfs" }
spk-cli-common = { path = '../common' }
spk-solve = { path = '../../spk-solve' }
spk-schema = { path = '../../spk-schema' }
spk-storage = { path = '../../spk-storage' }
strip-ansi-escapes = { version = "0.1.1" }
tokio = { workspace = true, features = ["rt"] }
tracing = { workspace = true }

[dev-dependencies]
rstest = { workspace = true }
