[package]
authors = ["Ryan Bottriell <rbottriell@imageworks.com>"]
edition = "2021"
name = "spk-cli-group1"
version = "0.36.0"

[features]
sentry = ["spk-solve/sentry"]

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
clap = { workspace = true }
colored = { workspace = true }
futures = "0.3.9"
itertools = "0.10"
serde = { version = "1.0.117", features = ["derive"] }
serde_json = "1.0.57"
serde_yaml = "0.8.17"
spfs = { version = '0.34.6', path = "../../spfs" }
spk-cli-common = { path = '../common' }
spk-solve = { path = '../../spk-solve' }
spk-schema = { path = '../../spk-schema' }
spk-storage = { path = '../../spk-storage' }
tokio = { workspace = true, features = ["rt"] }
tracing = { workspace = true }

[dev-dependencies]
rstest = "0.15.0"
