[package]
authors = ["Ryan Bottriell <rbottriell@imageworks.com>"]
edition = { workspace = true }
name = "spk-storage"
version = { workspace = true }

[dependencies]
async-trait = { workspace = true }
colored = { workspace = true }
dashmap = "5.4.0"
data-encoding = "2.3.0"
enum_dispatch = "0.3.8"
format_serde_error = {version = "0.3", default_features = false, features = ["serde_yaml", "colored"]}
futures = "0.3.9"
glob = "0.3.0"
ignore = "0.4.18"
indexmap = "1.7.0"
itertools = "0.10"
lazy_static = { workspace = true }
nom = "7.1"
once_cell = { workspace = true }
regex = "1.5.4"
relative-path = "1.3.2"
ring = "0.16.15"
rstest = "0.15.0"
serde = { workspace = true, features = ["derive"] }
serde_json = "1.0.57"
serde_yaml = "0.8.17"
sentry = { workspace = true, optional = true }
spfs = { version = '0.34.6', path = "../spfs" }
spk-schema = { path = "../spk-schema" }
sys-info = "0.9.0"
tar = "0.4.30"
tempfile = "3.3"
thiserror = "1.0"
tokio = { workspace = true, features = ["rt"] }
tracing = { workspace = true }
tracing-subscriber = "0.2.16"
url = "2.2"
