[package]
authors = ["Ryan Bottriell <rbottriell@imageworks.com>"]
edition = "2021"
name = "spk-storage"
version = "0.36.0"

[dependencies]
async-trait = "0.1"
colored = "2.0"
data-encoding = "2.3.0"
enum_dispatch = "0.3.8"
futures = "0.3.9"
glob = "0.3.0"
ignore = "0.4.18"
indexmap = "1.7.0"
itertools = "0.10"
lazy_static = "1.4.0"
nom = "7.1"
once_cell = "1.8.0"
regex = "1.5.4"
relative-path = "1.3.2"
ring = "0.16.15"
rstest = "0.15.0"
serde = { version = "1.0.117", features = ["derive"] }
serde_derive = "1.0.118"
serde_json = "1.0.57"
serde_yaml = "0.8.17"
sentry = { version = "0.27.0", optional = true }
spfs = { version = '0.34.6', path = "../spfs" }
spk-schema = { path = "../spk-schema" }
sys-info = "0.9.0"
tar = "0.4.30"
tempfile = "3.3"
thiserror = "1.0"
tokio = { version = "1.20", features = ["rt"] }
tracing = "0.1.35"
tracing-subscriber = "0.2.16"
url = "2.2"
