[package]
authors = { workspace = true }
edition = { workspace = true }
name = "spk-storage"
version = { workspace = true }
license-file = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }
readme = { workspace = true }
description = { workspace = true }

[lints]
workspace = true

[features]
migration-to-components = ["spk-schema/migration-to-components"]

[dependencies]
arc-swap = { workspace = true }
async-trait = { workspace = true }
async-stream = { workspace = true }
colored = { workspace = true }
dashmap = { workspace = true }
data-encoding = "2.3.0"
enum_dispatch = { workspace = true }
format_serde_error = { workspace = true, default-features = false, features = [
    "colored",
    "serde_yaml",
] }
futures = { workspace = true }
glob = { workspace = true }
ignore = "0.4.18"
indexmap = { workspace = true }
itertools = { workspace = true }
miette = { workspace = true }
nom = { workspace = true }
nom-supreme = { workspace = true }
once_cell = { workspace = true }
paste = { workspace = true }
regex = { workspace = true }
relative-path = { workspace = true }
ring = { workspace = true }
rstest = { workspace = true }
sentry = { workspace = true, optional = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
spfs = { workspace = true }
spk-schema = { workspace = true }
spk-workspace = { workspace = true }
sys-info = "0.9.0"
tar = "0.4.30"
tempfile = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["rt"] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
ulid = { workspace = true }
url = "2.2"
variantly = { workspace = true }
