[package]
authors = ["Ryan Bottriell <rbottriell@imageworks.com>"]
edition = { workspace = true }
name = "spk-solve-graph"
version = { workspace = true }

[dependencies]
async-recursion = "1.0"
async-stream = "0.3"
async-trait = { workspace = true }
colored = "2.0"
ctrlc = "3.2"
dyn-clone = "1.0"
futures = "0.3.9"
itertools = "0.10"
once_cell = "1.8"
priority-queue = "1.2"
serde_json = "1.0"
spfs = { version = '0.34.6', path = "../../../spfs" }
spk-solve-package-iterator = { path = "../package-iterator" }
spk-solve-solution = { path = "../solution" }
spk-schema = { path = "../../../spk-schema" }
spk-storage = { path = "../../../spk-storage" }
thiserror = "1.0"
tokio = { workspace = true, features = ["rt"] }
tracing = { workspace = true }

[dev-dependencies]
rstest = { workspace = true }
serde_yaml = "0.8.17"
