[package]
authors = { workspace = true }
edition = { workspace = true }
name = "spk-solve-graph"
version = { workspace = true }

[features]
migration-to-components = [
    "spk-config/migration-to-components",
    "spk-solve-package-iterator/migration-to-components",
    "spk-solve-solution/migration-to-components",
    "spk-schema/migration-to-components",
    "spk-storage/migration-to-components",
]

[dependencies]
async-recursion = "1.0"
async-stream = "0.3"
async-trait = { workspace = true }
colored = { workspace = true }
ctrlc = "3.2"
dyn-clone = { workspace = true }
futures = { workspace = true }
itertools = "0.10"
once_cell = { workspace = true }
priority-queue = "1.2"
serde_json = { workspace = true }
spfs = { path = "../../../spfs" }
spk-config = { path = "../../../spk-config" }
spk-solve-package-iterator = { path = "../package-iterator" }
spk-solve-solution = { path = "../solution" }
spk-schema = { path = "../../../spk-schema" }
spk-storage = { path = "../../../spk-storage" }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["rt"] }
tracing = { workspace = true }

[dev-dependencies]
rstest = { workspace = true }
serde_yaml = { workspace = true }
