[package]
authors = { workspace = true }
edition = { workspace = true }
name = "spk-cmd-explain"
version = { workspace = true }

[lints]
workspace = true

[dependencies]
miette = { workspace = true, features = ["fancy"] }
async-trait = { workspace = true }
clap = { workspace = true }
spk-cli-common = { workspace = true }
# The dependency on spfs can be removed after the deprecated runtime flags are
# removed.
spfs = { workspace = true }
tokio = { workspace = true, features = ["rt"] }
# The dependency on tracing can be removed after the deprecated runtime flags
# and deprecation warnings are removed.
tracing = { workspace = true }
