[package]
authors = { workspace = true }
edition = { workspace = true }
name = "spk-schema"
version = { workspace = true }
license-file = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }
readme = { workspace = true }
description = { workspace = true }

[lints]
workspace = true

[features]
migration-to-components = ["spk-schema-foundation/migration-to-components"]

[dependencies]
bracoxide = { workspace = true }
config = { workspace = true }
data-encoding = "2.3"
dunce = { workspace = true }
enum_dispatch = { workspace = true }
format_serde_error = { workspace = true, default-features = false, features = [
    "serde_yaml",
    "colored",
] }
ignore = "0.4.18"
indexmap = { workspace = true }
is_default_derive_macro = { workspace = true }
itertools = { workspace = true }
nom = { workspace = true }
nom-supreme = { workspace = true }
regex = { workspace = true }
relative-path = { workspace = true }
ring = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_yaml = { workspace = true }
serde_json = { workspace = true }
spfs = { workspace = true }
shellexpand = "3.1.0"
spk-config = { workspace = true }
spk-schema-foundation = { workspace = true }
spk-schema-tera = { workspace = true }
strum = { workspace = true }
sys-info = "0.9.0"
tempfile = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
url = { workspace = true, features = ["serde"] }
miette = { workspace = true }

[dev-dependencies]
proptest = "1.0.0"
rstest = { workspace = true }
