[package]
authors = ["Ryan Bottriell <rbottriell@imageworks.com>"]
edition = "2021"
name = "spk-schema"
version = "0.36.0"

[dependencies]
data-encoding = "2.3"
enum_dispatch = "0.3.8"
ignore = "0.4.18"
indexmap = "1.7"
itertools = "0.10"
nom = "7.1"
regex = "1.5"
relative-path = "1.3"
serde = { version = "1.0", features = ["derive"] }
serde_derive = "1.0"
serde_yaml = "0.8.17"
serde_json = "1.0"
spfs = { version = '0.34.6', path = "../spfs" }
spk-schema-foundation = { path = "./crates/foundation" }
spk-schema-ident = { path = "./crates/ident" }
spk-schema-validators = { path = "./crates/validators" }
sys-info = "0.9.0"
tempfile = "3.3"
thiserror = "1.0"
tracing = "0.1.35"

[dev-dependencies]
proptest = "1.0.0"
rstest = "0.15.0"
