[package]
authors = { workspace = true }
edition = { workspace = true }
name = "spk-schema"
version = { workspace = true }

[features]
migration-to-components = ["spk-schema-foundation/migration-to-components"]

[dependencies]
data-encoding = "2.3"
enum_dispatch = "0.3.8"
execute = "0.2.12"
format_serde_error = { version = "0.3", default_features = false, features = [
    "serde_yaml",
    "colored",
] }
ignore = "0.4.18"
indexmap = "1.7"
itertools = "0.10"
nom = { workspace = true }
regex = "1.5"
relative-path = "1.3"
serde = { workspace = true, features = ["derive"] }
serde_yaml = { workspace = true }
serde_json = { workspace = true }
spfs = { path = "../spfs" }
shellexpand = "3.1.0"
spk-config = { path = "../spk-config" }
spk-schema-foundation = { path = "./crates/foundation" }
spk-schema-ident = { path = "./crates/ident" }
spk-schema-validators = { path = "./crates/validators" }
spk-schema-liquid = { path = "./crates/liquid" }
sys-info = "0.9.0"
tempfile = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
proptest = "1.0.0"
rstest = { workspace = true }
