[package]
authors = { workspace = true }
edition = { workspace = true }
name = "spk-cli-group4"
version = { workspace = true }

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
clap = { workspace = true }
colored = { workspace = true }
futures = { workspace = true }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
itertools = "0.10"
spfs = { path = "../../spfs" }
spk-cli-common = { path = '../common' }
spk-schema = { path = '../../spk-schema' }
spk-solve = { path = '../../spk-solve' }
spk-storage = { path = '../../spk-storage' }
strum = { workspace = true }
tokio = { workspace = true, features = ["rt"] }
tracing = { workspace = true }
