[package]
authors = { workspace = true }
edition = { workspace = true }
name = "spk-schema-validators"
version = { workspace = true }

[features]
migration-to-components = [
    "spk-schema-foundation/migration-to-components",
    "spk-schema-ident/migration-to-components",
]

[dependencies]
data-encoding = "2.3.0"
ignore = "0.4.18"
indexmap = "1.7.0"
itertools = "0.10"
nom = { workspace = true }
regex = "1.5.4"
relative-path = "1.3.2"
ring = "0.16.15"
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
spfs = { path = "../../../spfs" }
spk-schema-foundation = { path = "../foundation" }
spk-schema-ident = { path = "../ident" }
sys-info = "0.9.0"
tempdir = "0.3.7"
thiserror = { workspace = true }
tracing = { workspace = true }
