name: Lint & Test

on: push

env:
  CARGO_TERM_COLOR: always

jobs:
  lint-rust:
    runs-on: ubuntu-latest
    env:
      SPFS_PULL_USERNAME: ${{ secrets.SPFS_PULL_USERNAME }}
      SPFS_PULL_PASSWORD: ${{ secrets.SPFS_PULL_PASSWORD }}
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt-get install -y libcap-dev
      - name: Patch spfs Pull Auth
        run: sed -i "s|github.com|$SPFS_PULL_USERNAME:$SPFS_PULL_PASSWORD@github.com|" Cargo.toml
      - name: Lint Rust Code
        run: make lint-rust
  test:
    runs-on: ubuntu-18.04
    steps:
      # essentially the goal is to run 'spfs run - -- pytest'
      # but we need to install spfs, have the spfs source code,
      # get the pipenv setup and then run this from within the pipenv...
      # all in the right version of a centos container
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # to work with tests
      - name: Download Deps
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{secrets.SPFS_PULL_PASSWORD}}
          workflow: rpm.yml
          workflow_conclusion: success
          # This branch should match the version of spfs being used
          # in Cargo.toml.
          branch: release-0.34.1
          name: Binary RPM
          path: deps
          repo: imageworks/spfs
      - name: Run Unit Tests
        env:
          SPFS_PULL_USERNAME: ${{ secrets.SPFS_PULL_USERNAME }}
          SPFS_PULL_PASSWORD: ${{ secrets.SPFS_PULL_PASSWORD }}
        run: docker run
          -e SPFS_PULL_USERNAME
          -e SPFS_PULL_PASSWORD
          -e HOME=/root
          -e CI
          --rm
          --privileged
          --net host
          -v $PWD:/source
          centos:7 bash -ex /source/.github/scripts/unittests.sh
